title: Neume Sampler
description: Neume sampler demonstration
github_username: craigsapp/neume-sampler
url: "https://neume-sampler.sapp.org"

theme: minima
#architect
#cayman
#dinky
#hacker
#leap day
#merlot
#midnight
#minimal
#modernist
#slate
#tactile
#time machine


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


